#!/bin/bash

# try building max times
max=3
for i in $(seq 1 $max) ; do
	xbuild && break
	if [ $i -eq 3 ] ; then
		echo "Unable to build umbraco."
		exit 1
	fi
done

echo "Successfully built umbraco."
exit 0
